apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vr23d1zve-python-gitops
  description: This is GitOps manifest for vr23d1zve-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vr23d1zve-python
    backstage.io/kubernetes-id: vr23d1zve-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/vr23d1zve-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vr23d1zve-python
