apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vr23d1zve-python
  janus-idp.io/tekton: vr23d1zve-python
  backstage.io/kubernetes-id: vr23d1zve-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vr23d1zve-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
