apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vr23d1zve-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vr23d1zve-python 
  name: vr23d1zve-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vr23d1zve-python 
